### ISSUE TITLE
Use an options object instead of global switches.

### ISSUE THREAD

**Issue by kikito** [mpx/lua-cjson#12]
Currently cjson uses global library settings:

    cjson.decode_invalid_numbers([setting])
    cjson.encode_invalid_numbers([setting])
    cjson.encode_keep_buffer([keep])
    cjson.encode_max_depth([depth])
    cjson.decode_max_depth([depth])
    cjson.encode_sparse_array([convert[, ratio[, safe]]])

This interface presents the problem of storing some state on the library. This is not ideal, since the output of `cjson.encode` and `cjson.decode`, when called with the same parameters, will change depending on those global settings. That is undesirable in lots of scenarios.

I propose an interface that, while allowing the same functionality, does not store any state on the library itself, and makes `cjson.encode` and `cjson.decode` deterministic: Add a (non-mandatory) `options` parameter to both.

    cjson.encode(value, options)
    cjson.decode(str, options)

For example:

    cjson.decode("{'a' = 1}", {invalid_numbers = true})
    cjson.encode({a = 1}, {depth = 1})

I would provide a pull request for this myself, but again I lack the necessary C skills to do so.

Please consider this as an enhancement request. Since this would be an interface-breaking change, I would suggest including it on a 3.x version.

**Comment by daurnimator** [comment]
It would be great to be API compatible with dkjson: http://dkolf.de/src/dkjson-lua.fsl/wiki?name=Documentation

**Comment by brimworks** [comment]
AFAIK, the library has always supported non-global configurations, you simply need to new() a new CJson encoder/decoder like this:

```lua
local my_parser = cjson.new()
my_parser.encode_invalid_numbers(true)
my_parser.decode_invalid_numbers(true)
my_parser.decode("...")
my_parser.encode({})
```

**Comment by kikito** [comment]
Thanks a lot!
