### ISSUE TITLE
option for indented output

### ISSUE THREAD

**Issue by capr** [mpx/lua-cjson#19]
Hi Mark,

Only minimified output is possible?

An option for indented output would be nice.

Thanks,
Cosmin.

**Comment by mpx** [comment]
Lua CJSON aims to be fast/standards compliant and my early testing showed custom indent support had reasonable performance hit. I've been using an external filter to view output with indentation (Eg, `python -mjson.tool`).

This could be revisited in future, but I don't have any current plans.
