### ISSUE TITLE
lua-cjson escapes slashes

### ISSUE THREAD

**Issue by vitek** [mpx/lua-cjson#2]
Hi!

Why does lua-cjson escape slashes:

```
> cjson = require 'cjson'
> print(cjson.encode('/'))
"\/"
```

Is that a bug?

**Comment by chunpu** [comment]
so `/` is a control-character then...

**Comment by ktalebian** [comment]
@ignacio what if you are doing 

```lua
cjson.encode({url =  "https://google.com})
```
This also encodes the `/`, but I'm trying to stringify this table/json object.
