### ISSUE TITLE
Call decode could result in crash

### ISSUE THREAD

**Issue by hcaihao** [mpx/lua-cjson#29]
local cjson = require "cjson"
while true do
        local t = {"a", "b", "c"}
        local s = cjson.encode(t)
        local value = cjson.decode(s) --Crash every time
end

**Comment by hcaihao** [comment]
local cjson = require "cjson"
while true do
        local t = {"a", "b", "c"}
        local s = cjson.encode(t)
end


local cjson = require "cjson"
while true do
        local s = [[ ["a","b","c"] ]]
        local t = cjson.decode(s)
        local text = cjson.encode(t)
end


But this two cases is ok.

**Comment by mpx** [comment]
Thanks for the report. Unfortunately I'm unable to reproduce the problem
(Lua 5.2.2, Linux, x86_64). The example provided works fine with no
crashes/memory leaks. Can you please provide some more details?

- What version of Lua?
- What platform/OS?
- How Lua CJSON built?

Does it work after a clean rebuild of Lua CJSON?

Also, do the unit tests included in the Lua CJSON distribution succeed?

**Comment by hcaihao** [comment]
I tested in
lua-5.1.4 & lua-5.1.5
Win764 + VS2013 & VS2010(Modified follow https://github.com/mpx/lua-cjson/pull/21/files) 
Def file:
"LIBRARY	"cjson"
EXPORTS
luaopen_cjson"

Build with dll.

**Comment by hcaihao** [comment]
This is my exe code:


#include "stdafx.h"
#include <string>

extern "C"
{
#include "lua.h"
#include "lualib.h"
#include "lauxlib.h"
};

lua_State* g_pLua = NULL;

int _tmain(int argc, _TCHAR* argv[])
{

	std::string script = R"(
local cjson = require "cjson"
while true do
local t = {"a", "b", "c"}
local s = cjson.encode(t)
local value = cjson.decode(s) --Crash every time
end
)";

	// Register Lua functions
	g_pLua = lua_open();
	luaL_openlibs(g_pLua);

	int error = luaL_dostring(g_pLua, script.c_str());
	//int error = luaL_dofile(g_pLua, std::string(g_appPath + "\\script.lua").c_str());
	if (error != 0)
	{
		const char* scriptError = lua_tostring(g_pLua, -1);

		throw std::exception(scriptError);
	}

	lua_close(g_pLua);

	return 0;
}

**Comment by hcaihao** [comment]
I found the problem is when I static link lua(exe link lua.lib) the crash happened. 

Is there any method to include cjson function all in one exe?

**Comment by mpx** [comment]
Yes, this should work, but I'm not familiar with Windows or Visual Studio specifics.

There are some common gotchas when linking Lua and plugins (eg, linking the runtime multiple times, or different Lua versions). I'd recommend checking the Lua website / mailing list archives.
