### ISSUE TITLE
Crash when use the value from cjson.decode

### ISSUE THREAD

**Issue by zhangpeihao** [mpx/lua-cjson#3]
I write a test:
	emptyValue = {}
	emptyValueText = cjson.encode(emptyValue)
	print("empty value text is: " .. emptyValueText)
	emptyValueNew = cjson.decode(emptyValueText)
	print("type(emptyValueNew) is " .. type(emptyValueNew))
	emptyValueNew.newMember = "emptyValueNew string"
	print("emptyValueNew.newMember = " .. emptyValueNew.newMember)

Program crashed after print: "type(emptyValueNew) is table"

**Comment by hcaihao** [comment]
issue #29 will reproduce this bug.

**Comment by mpx** [comment]
Closing, no detail to reproduce.
