### ISSUE TITLE
Transfer repository ownership due to inactivity

### ISSUE THREAD

**Issue by phoenixenero** [mpx/lua-cjson#34]
This repo should be transferred to a new maintainer since the current one is highly inactive. Anyone willing to do that?

**Comment by brimworks** [comment]
I'm willing to... my master is already ahead of the mpx master branch that has fixes for Windows builds, a new decode_big_numbers_as_strings option, and a "universal" NULL and array types. Specifically, any value with a metatable that contains __name field set to "null" will be interpreted as a null. Similarly, if the metatable contains __name field set to "array" it is interpreted as an array.

I needed the "universal" null and array types to support interchange with YAML serialization format (decode YAML, then encode as JSON for example).

Just let me know what the "next steps" are on this.

Thanks,
-Brian

**Comment by xpol** [comment]
I think the follow actions needed:

0. Ask if @mpx still want to maintain this project or not.
1. Remove git fork relationship, and add description in README.
2. Make new release to luarocks.org (may needs to concat https://luarocks.org/modules/leafo to do this.)
3. Post a announcement email in Lua mailing list <lua-l@lists.lua.org>

**Comment by mpx** [comment]
Yes, I'm still maintaining Lua CJSON, but I'm open to assistance.

I've added some comments to your numbers_as_strings pull request.
